base-url=http://localhost:8080


spring.main.allow-bean-definition-overriding=true
 
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.messages.basename=messages
server.error.include-binding-errors=always
server.servlet.session.persistent=false

#DB 
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;NON_KEYWORDS=USER;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
 
#spring.data.jpa.repositories.bootstrap-mode=default
 
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=NULL
spring.mail.password=NULL

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=NULL
spring.security.oauth2.client.registration.google.client-secret=NULL
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar.events
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.config.import=optional:file:./application-local.properties

# Fuer PayPal-Integration
spring.profiles.active=local

# Open API / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
security.jwt.secret-key=shouldbeinLocalproperties

app.security.remember-me.key=iwasdoofes

# Nur Test fuer Dashboard-Gesamteinnahmen-Update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true





